# Generated by Django 4.0.2 on 2022-03-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.TextField(max_length=50)),
                ('gid', models.TextField(max_length=50)),
                ('amount', models.FloatField()),
                ('interest', models.FloatField()),
                ('returnperiod', models.IntegerField()),
                ('income', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'Approved_loan',
            },
        ),
        migrations.CreateModel(
            name='ATM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.TextField(max_length=50)),
                ('name', models.TextField(max_length=50)),
                ('card', models.BigIntegerField()),
                ('cvv', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'atm',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=120)),
                ('lastname', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=50)),
                ('problem', models.TextField()),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'contact',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=120)),
                ('mobile', models.TextField(max_length=50)),
                ('gid', models.TextField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('amount', models.FloatField()),
                ('type', models.TextField(max_length=10)),
                ('gender', models.TextField(max_length=20)),
                ('date', models.DateTimeField()),
                ('nominee', models.TextField(max_length=50)),
                ('dob', models.TextField(max_length=15)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.TextField(max_length=50)),
                ('gid', models.TextField(max_length=50)),
                ('amount', models.FloatField()),
                ('purpose', models.TextField(max_length=50)),
                ('approved', models.TextField(max_length=2)),
                ('estatus', models.TextField(max_length=50)),
                ('prevloan', models.TextField(max_length=50)),
                ('returnperiod', models.IntegerField()),
                ('income', models.IntegerField()),
                ('remark', models.TextField(max_length=80)),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'applied_loan',
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.TextField(max_length=50)),
                ('type', models.TextField(max_length=10)),
                ('amount', models.FloatField()),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'operation',
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.TextField(max_length=50)),
                ('receiver', models.TextField(max_length=50)),
                ('amount', models.FloatField()),
                ('remark', models.TextField(max_length=50)),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'transfer',
            },
        ),
        migrations.CreateModel(
            name='Updation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.TextField(max_length=50)),
                ('type', models.TextField(max_length=50)),
                ('prevdata', models.TextField(max_length=50)),
                ('newdata', models.TextField(max_length=50)),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'updation',
            },
        ),
    ]
